### ISSUE TITLE
getStream->getContents is empty

### ISSUE THREAD

**Issue by Enjoyzz** [httpsoft/http-message#12]
**Description**
See comment https://github.com/httpsoft/http-message/commit/a01ec15240e60f07f5c122c358d681b5f760731c#r78665198
Maybe I'm wrong, but everything works in guzzle and Nyholm, but not here (((

**Possible solution**
"r+" mode is needed , otherwise content is empty

**Additional info**

| Q                | A
| ---------------- | ---
| Package version  |  1.0.9
| PHP version      |  8.0
| Operating system | Ubuntu

**Comment by devanych** [comment]
Thanks. I'll check it out one of these days.

**Comment by Enjoyzz** [comment]
PR with test https://github.com/httpsoft/http-message/pull/13#issue-1309093332
