### ISSUE TITLE
Add support for HTTP/3.0

### ISSUE THREAD

**Issue by liviuconcioiu** [httpsoft/http-message#30]
**Description**
`Unsupported HTTP protocol version "3.0" provided. The following strings are supported: "1.0", "1.1", "2.0", "2".`

**How to reproduce**
Use the code over HTTP/3.0.

**Expected result**
It should not throw that exception.

**Possible solution**
https://github.com/httpsoft/http-message/blob/98ab6afd2328f31d4eb3d0379567dad6251fa6a6/src/MessageTrait.php#L39

```diff
-    private static array $supportedProtocolVersions = ['1.0', '1.1', '2.0', '2'];
+    private static array $supportedProtocolVersions = ['1.0', '1.1', '2.0', '2', '3.0', '3'];
```

**Additional info**

| Q                | A
| ---------------- | ---
| Package version  | 1.1.4
| PHP version      | 8.3.7
| Operating system | Linux

**Comment by devanych** [comment]
Thanks :+1:
