### ISSUE TITLE
normalizeHeaderName invalid argument exception

### ISSUE THREAD

**Issue by 8ctopus** [httpsoft/http-message#35]
**Description**

While reviewing my server php logs, I find from time to time the following exception in the package:

```txt
Uncaught InvalidArgumentException: `integer` is not valid header name.
in /vendor/httpsoft/http-message/src/MessageTrait.php:384
Stack trace: #0 /vendor/httpsoft/http-message/src/MessageTrait.php(357): HttpSoft\\Message\\ServerRequest->normalizeHeaderName()
#1 /vendor/httpsoft/http-message/src/RequestTrait.php(233): HttpSoft\\Message\\ServerRequest->registerHeaders()
#2 /vendor/httpsoft/http-message/src/ServerRequest.php(84): HttpSoft\\Message\\ServerRequest->init()
#3 /vendor/httpsoft/http-server-request/src/ServerRequestCreator.php(41): HttpSoft\\Message\\ServerRequest->__construct()
#4 /public/router.php(38): HttpSoft\\ServerRequest\\ServerRequestCreator::createFromGlobals()
#5 {main} thrown in /vendor/httpsoft/http-message/src/MessageTrait.php on line 384
```

in the apache access log, I have the following log for the same ip:

```
174.138.20.249 - - [17/Sep/2024:09:50:25 +0200] "GET /index.php HTTP/1.1" 500 3848 "copytrans.com.mx" "Mozilla/5.1 (Windows NT 6.0; WOW64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/58.0.1145.75 Safari/537.37"
```

**How to reproduce**

pass an integer as header name instead of a string? I unfortunately don't have the headers of the above request.

**Expected result**

I understand the request is malformed, however:

- Should an exception be thrown in such as case?
- or should the value be casted to string?
- or should the specific header be ignored?

**Additional info**

| Package version  | 1.1.5
| PHP version      |  8.3
| Operating system | Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1070-aws x86_64)

**Comment by devanych** [comment]
This is not a bug. The title name must be a string: https://datatracker.ietf.org/doc/html/rfc7230#section-3.2

What you are sending there is already your problem, this package does not validate it

**Comment by 8ctopus** [comment]
Yes, I understand the header must be a string, however what I'm asking is if an exception should be thrown, or whether you should attempt casting to string or simply ignore the header in question.

With the current implementation, such requests are simply not processed since they throw an exception.

If you prefer to answer in Russian, it is fine as I do understand.

**Comment by devanych** [comment]
According to the PSR-7, an `InvalidArgumentException` exception should be thrown:
https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L130C38-L130C77

**Comment by 8ctopus** [comment]
Yes are right, the psr-7 standard should be respected.
Большое вам спасибо за то, что нашли время ответить.
